# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # Creates other Mobius API services
    mobius.api_factory:
        class: 'AppBundle\Mobius\MobiusApiServiceFactory'

    # Interacts with the DApp store
    mobius.app_store:
        class: 'ZuluCrypto\MobiusApi\Model\AppStore'
        factory: 'mobius.api_factory:createAppApi'
        arguments: ['%mobius_api_key%', '%mobius_app_uid%']

